2025-08-17 00:06:58,192 [INFO] Step-1: Folder created: uploads/1387d789-ddbd-41be-b300-d258a5d6a598
2025-08-17 00:08:09,353 [INFO] Using Python executable: venv1/bin/python3
2025-08-17 00:08:09,353 [INFO] Step-2: File sent {'question.txt': 'uploads/1387d789-ddbd-41be-b300-d258a5d6a598/question.txt'}
2025-08-17 00:08:09,354 [INFO] 🤖 Step-1: Getting scrap code and metadata from llm. Tries count = 0
2025-08-17 00:08:15,774 [INFO] 🤖 Step-1: Successfully parsed response from LLM.
2025-08-17 00:08:15,774 [INFO] 💻 Step-3: Entering loop
2025-08-17 00:08:15,774 [INFO] 💻 Loop-1: Running LLM code.
2025-08-17 00:08:16,142 [ERROR] ❌💻 Loop-1: Code execution failed: ❌ Execution error: Traceback (most recent call last): File "/home/raushan/TDS_project2/uploads/1387d789-ddbd-41be-b300-d258a5d6a598/job_/script.py", line 3, in <module> df = pd.read_csv('sample-sales.csv') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv return _read(filepath_or_buffer, kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read parser = TextFileReader(filepath_or_buffer, **kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__ self._engine = self._make_engine(f, self.engine) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine self.handles = get_handle( ^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle handle = open( ^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'sample-sales.csv'
2025-08-17 00:08:16,143 [INFO] 🤖 Loop-1: Inside Loop LLM call.
2025-08-17 00:08:21,140 [INFO] 💻 Loop-2: Running LLM code.
2025-08-17 00:08:21,494 [ERROR] ❌💻 Loop-2: Code execution failed: ❌ Execution error: Traceback (most recent call last): File "/home/raushan/TDS_project2/uploads/1387d789-ddbd-41be-b300-d258a5d6a598/job_/script.py", line 3, in <module> df = pd.read_csv('uploads/1387d789-ddbd-41be-b300-d258a5d6a598/sample-sales.csv') ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv return _read(filepath_or_buffer, kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 620, in _read parser = TextFileReader(filepath_or_buffer, **kwds) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__ self._engine = self._make_engine(f, self.engine) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine self.handles = get_handle( ^^^^^^^^^^^ File "/home/raushan/TDS_project2/venv1/lib/python3.12/site-packages/pandas/io/common.py", line 873, in get_handle handle = open( ^^^^^ FileNotFoundError: [Errno 2] No such file or directory: 'uploads/1387d789-ddbd-41be-b300-d258a5d6a598/sample-sales.csv'
2025-08-17 00:08:21,494 [INFO] 🤖 Loop-2: Inside Loop LLM call.
2025-08-17 00:09:17,851 [INFO] 💻 Loop-3: Running LLM code.
2025-08-17 00:09:18,620 [INFO] ✅💻 Loop-3: Code executed successfully.
2025-08-17 00:09:18,620 [INFO] ✅📁 Loop-3: Found result files.
2025-08-17 00:09:18,620 [INFO] 🤖 Loop-3: Checking result validity.
2025-08-17 00:09:26,613 [INFO] ✅ Loop-3: Validation successful, no re-run needed.
2025-08-17 00:09:26,613 [INFO] 💻 Step-6: Running final code.
2025-08-17 00:09:26,630 [INFO] 📁 Step-7: Reading result.json
2025-08-17 00:09:26,630 [INFO] ✅📁 Step-7: send result back
